"""Generate the promtool alert-rule test fixture from REAL captured stage
registries — the crux of the Phase-7 promtool decision (specs/phase-7.md fix #1):
the threshold-crossing numbers come from `make metrics-capture`, never
hand-authored. The .prom inputs live under data/out/<profile>/metrics/
(gitignored); the generated fixture is committed and read by `make test-alerts`.

Regenerate after capturing both profiles on clean single-profile stacks (they
share conversion_id space — DECISIONS Phase 5):

    make down && make lake-reset CONFIRM=yes && make up \
        && make seed PROFILE=tiny && make metrics-capture PROFILE=tiny
    make down && make lake-reset PROFILE=long_delay CONFIRM=yes && make up \
        && make seed PROFILE=long_delay && make metrics-capture PROFILE=long_delay
    (a CLEAN lake each time — since Phase 17 the reconcile candidates are the lake's
    current rows, so a capture over a populated lake does not reproduce)
    uv run python observability/gen_alert_fixtures.py
"""

from pathlib import Path

from prometheus_client.parser import text_string_to_metric_families

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "observability/rules/tests/alerts_test.yml"

# The five series the four alerts read.
SERIES = [
    "resolve_input_backlog",
    "engine_conversions_attributed_total",
    "engine_conversions_processed_total",
    "engine_watermark_lag_seconds",
    "reconcile_restatement_roas_abs_delta",
]

ALERTS = ["ConsumerLag", "WatermarkStall", "MatchRateOutOfBand", "RestatementMagnitude"]

# Capture profile → (metrics dir, alerts expected to fire). long_delay's knobs
# (volume, 300-min late injector, >7d causal delays, long-window recovery) trip
# all four; tiny trips only RestatementMagnitude — since Phase 16 its 5 shared-IP
# conversions are deferred hot and credited by the reconcile pass, which restates
# a campaign ROAS by ~12.9 (> the 1.0 threshold); the other three stay silent on
# tiny, so each of those is proven to fire on a real knobbed run AND stay silent
# on another. The fire/silent expectation is the test's claim; promtool
# independently checks the RULES produce it from the captured numbers (no
# circularity — the generator never evaluates a threshold).
PROFILES = [
    ("long_delay", "data/out/long_delay/metrics", ALERTS),
    ("tiny", "data/out/tiny/metrics", ["RestatementMagnitude"]),
]


def read_series(metrics_dir: Path) -> dict[str, float]:
    """Parse the stage .prom dumps and pull the five series (exact-name match, so
    counter `_created` companions are ignored). Missing any → the capture didn't
    run; fail loudly rather than emit a fixture with stale/absent numbers."""
    vals: dict[str, float] = {}
    for prom in sorted(metrics_dir.glob("*.prom")):
        for family in text_string_to_metric_families(prom.read_text()):
            for sample in family.samples:
                if sample.name in SERIES:
                    vals[sample.name] = sample.value
    missing = [s for s in SERIES if s not in vals]
    if missing:
        raise SystemExit(f"{metrics_dir}: missing {missing} — run make metrics-capture")
    return vals


def _fmt(v: float) -> str:
    """Preserve the captured value exactly; render integers without a `.0`."""
    return repr(int(v)) if v == int(v) else repr(v)


def render() -> str:
    lines = [
        "# GENERATED by observability/gen_alert_fixtures.py from REAL captured",
        "# stage registries (make metrics-capture) — do NOT hand-edit the values.",
        "# Provenance: specs/phase-7.md fix #1. Regenerate after a capture.",
        "rule_files:",
        "  - ../alerts.yml",
        "evaluation_interval: 1m",
        "tests:",
    ]
    for name, mdir, expected in PROFILES:
        vals = read_series(ROOT / mdir)
        claim = f"fires {', '.join(expected)}" if expected else "all silent"
        lines += [
            f"  # {name}: {claim} (real captured values, held across the window)",
            "  - interval: 1m",
            "    input_series:",
        ]
        for s in SERIES:
            # `+0x15` holds the captured value for 16 one-minute steps, so the
            # rules' `for: 5m` is satisfied well before the 10m eval.
            lines += [
                f"      - series: '{s}'",
                f"        values: '{_fmt(vals[s])}+0x15'",
            ]
        lines.append("    alert_rule_test:")
        for alert in ALERTS:
            lines += ["      - eval_time: 10m", f"        alertname: {alert}"]
            if alert in expected:
                lines += [
                    "        exp_alerts:",
                    "          - exp_labels:",
                    "              severity: warning",
                ]
            else:
                lines.append("        exp_alerts: []")
    return "\n".join(lines) + "\n"


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render())
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
