"""Measured scaling curve for the hot-window join state (Phase 14).

Teaching note — window-state occupancy and the memory budget. The engine keeps
every exposure of the last 7 days in processor memory so a late conversion can
still find the ad that caused it (the "hot window"). *Occupancy* is how many
exposures sit in that state at once; it is set by the arrival RATE, not the total
event count — `window_state ≈ exposure_rate × window_length × per-exposure-bytes`.
That product is the first wall the design hits: it grows with the rate and stops
fitting in one node's RAM long before anything else breaks. This probe measures
the one term SCALING.md used to guess — the per-exposure byte cost — so the
extrapolation to a real rate rests on a measured constant instead of a round
number.

Determinism (the trap this phase exists to avoid): the reported
`bytes_per_exposure` is a STRUCTURAL measure — the deep `sys.getsizeof` of the
retained hot-window state divided by its entry count — which is identical on every
re-run under a fixed seed and single thread. `tracemalloc` peak is allocation- and
GC-nondeterministic (it drifts with runtime timing), so it is reported as a
labeled cross-check column only and NEVER asserted. Same discipline as the Phase-7
`FINAL read_rows` fix.

Occupancy, not throughput: the curve dials event COUNT up across tiers (state
occupancy), which models `exposure_rate × window` directly. It is NOT a msgs/sec
throughput benchmark — that needs continuous follow, which is deferred and owned by
no phase (SCALING.md, DECISIONS Phase 5).

Offline, no compose: each tier is generated, resolved, deduped, and drained
through the real engine (`build_flow` + `run_main`, EOF-driven) in-process — the
same service-free idiom as the oracle suites. The probe only OBSERVES engine state
(it reads `engine_join_state_current` from Phase 7 and deep-sizes the retained
exposures); it never alters engine behavior or the state representation, so the
tiny golden stays byte-identical.
"""

import argparse
import sys
import tracemalloc
from dataclasses import dataclass
from pathlib import Path

from bytewax.testing import TestingSink, run_main

from producer.config import Profile, load_profile
from producer.generate import generate
from resolve.index import GraphIndex
from resolve.resolver import resolve_stream
from streaming import metrics
from streaming.attribute import ALLOWED_LATENESS, dedup_streams
from streaming.dataflow import build_flow

REPO_ROOT = Path(__file__).parent.parent
SCALING_MD = REPO_ROOT / "docs" / "SCALING.md"
BASE_PROFILE = "scale_curve"

# The curve tiers: exposures resident in the hot window. Same fixed event-time
# span at every tier (SPAN_HOURS < 7d, so nothing evicts and occupancy == count);
# the event COUNT is dialed up, which is what models a rising exposure rate.
TIERS = (1_000, 10_000, 100_000)

# Tier geometry, held fixed so only the count (and thus occupancy) changes.
SPAN_HOURS = 100.0  # < 7-day window → every exposure stays resident, no eviction
EXPOSURES_PER_HOUSEHOLD = 50  # realistic per-key density; households scale with count

# The measured extrapolation target (SCALING.md): a 25k/sec exposure rate (half of
# a 50k/sec stream) held for the 7-day window. The RATE is still an assumption —
# only the per-exposure byte cost below is measured.
EXTRAP_RATE_PER_SEC = 25_000
EXTRAP_WINDOW_SECONDS = 7 * 24 * 3600  # 604,800

_BEGIN = (
    "<!-- scale-curve:begin (generated by `make scale-curve` — do not edit by hand) -->"
)
_END = "<!-- scale-curve:end -->"


def deep_sizeof(obj: object, _seen: set[int] | None = None) -> int:
    """Recursive `sys.getsizeof`: an object plus everything it uniquely holds.
    Shared objects (interned category strings, e.g. a campaign_id reused across
    exposures) are counted once via an id() set, so the total is the real RAM the
    object graph occupies — deterministic for fixed content (same sharing pattern
    → same total, independent of the run's actual id() values)."""
    seen = set() if _seen is None else _seen
    oid = id(obj)
    if oid in seen:
        return 0
    seen.add(oid)
    size = sys.getsizeof(obj)
    if isinstance(obj, dict):
        for key, value in obj.items():
            size += deep_sizeof(key, seen) + deep_sizeof(value, seen)
    elif isinstance(obj, (list, tuple, set, frozenset)):
        for item in obj:
            size += deep_sizeof(item, seen)
    if hasattr(obj, "__dict__"):  # pydantic models store fields here
        size += deep_sizeof(vars(obj), seen)
    return size


@dataclass(frozen=True)
class CurvePoint:
    """One tier of the curve. The first five fields are the deterministic
    structural measure (asserted, re-run-identical); `tracemalloc_peak_bytes` is
    the labeled allocation cross-check (NEVER asserted)."""

    n_exposures: int
    exposures_in_window: int  # resident hot-window entries (== count; no eviction)
    structural_bytes: int  # deep_sizeof of the retained exposure state
    bytes_per_exposure: float  # structural_bytes / exposures_in_window
    join_state_current: int  # engine_join_state_current gauge (Phase 7), per household
    join_state_peak: int  # engine_join_state_size gauge (peak single-household)
    tracemalloc_peak_bytes: int  # cross-check only, not deterministic


def _tier_profile(base: Profile, n_exposures: int) -> Profile:
    """Derive a tier from the base volume profile: dial the event count to
    `n_exposures`, hold the event-time span fixed (`events_per_hour = count /
    SPAN_HOURS`), and scale households so per-household density stays realistic and
    the per-key drain stays cheap. Additive — the base profile is untouched."""
    households = max(1, n_exposures // EXPOSURES_PER_HOUSEHOLD)
    events = base.events.model_copy(
        update={
            "n_exposures": n_exposures,
            "events_per_hour": n_exposures / SPAN_HOURS,
            "organic_conversions": max(10, n_exposures // 1000),
        }
    )
    graph = base.graph.model_copy(update={"n_households": households})
    return base.model_copy(update={"events": events, "graph": graph})


def measure_tier(base: Profile, n_exposures: int) -> CurvePoint:
    """Generate → resolve → dedup → drain the engine over one tier, then measure
    the retained hot-window state structurally. Raises if eviction fired: the
    structural measure equates the retained state with the deduped input, which
    only holds when nothing aged out (guaranteed by SPAN_HOURS < window)."""
    profile = _tier_profile(base, n_exposures)
    stream = generate(profile, profile.seed)
    index = GraphIndex.from_households(stream.graph.households)
    resolved = resolve_stream(stream.conversions, index)
    exposures, resolved_dd, _ = dedup_streams(stream.exposures, resolved)

    metrics.EXPOSURES_EVICTED._value.set(0)
    metrics.reset_join_state_peak()
    tracemalloc.start()
    run_main(
        build_flow(
            exposures, resolved_dd, TestingSink([]), TestingSink([]), ALLOWED_LATENESS
        )
    )
    _, tm_peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    evicted = metrics.EXPOSURES_EVICTED._value.get()
    if evicted:
        raise RuntimeError(
            f"tier {n_exposures}: {evicted:.0f} exposures evicted — the retained "
            "state no longer equals the input; shorten SPAN_HOURS or the delay so "
            "the structural measure stays valid."
        )

    structural = deep_sizeof(exposures)
    return CurvePoint(
        n_exposures=n_exposures,
        exposures_in_window=len(exposures),
        structural_bytes=structural,
        bytes_per_exposure=structural / len(exposures),
        join_state_current=int(metrics.JOIN_STATE_CURRENT._value.get()),
        join_state_peak=int(metrics.JOIN_STATE_SIZE._value.get()),
        tracemalloc_peak_bytes=tm_peak,
    )


def run_curve(tiers: tuple[int, ...] = TIERS) -> list[CurvePoint]:
    base = load_profile(BASE_PROFILE)
    return [measure_tier(base, n) for n in tiers]


def render_table(points: list[CurvePoint]) -> str:
    header = (
        "| exposures in window | structural state | "
        "bytes/exposure (measured) | `engine_join_state_current` | "
        "`tracemalloc` peak (cross-check) |\n"
        "|---|---|---|---|---|\n"
    )
    rows = "".join(
        f"| {p.exposures_in_window:,} | {p.structural_bytes / 1e6:.1f} MB | "
        f"{p.bytes_per_exposure:.0f} B | {p.join_state_current} | "
        f"{p.tracemalloc_peak_bytes / 1e6:.1f} MB |\n"
        for p in points
    )
    return header + rows


def render_block(points: list[CurvePoint]) -> str:
    """The generated SCALING.md block: the measured constant, the curve table, and
    the TB extrapolation re-derived from the measured `bytes_per_exposure`. Only
    the per-exposure cost is measured; the rate and the multiplication stay
    extrapolation (order-of-magnitude sizing, not benchmarked capacity)."""
    per = [p.bytes_per_exposure for p in points]
    lo, hi = min(per), max(per)
    anchor = points[-1].bytes_per_exposure  # largest tier: most string-pooling
    total_exposures = EXTRAP_RATE_PER_SEC * EXTRAP_WINDOW_SECONDS
    tb = total_exposures * anchor / 1e12
    return (
        f"{_BEGIN}\n"
        f"**Measured** (`make scale-curve`, offline engine drain over the "
        f"`scale_curve` profile): the retained hot-window state costs "
        f"**~{anchor:.0f} B/exposure** ({lo:.0f}–{hi:.0f} B across the curve, "
        f"structural — deep `sys.getsizeof` of the retained exposures ÷ entry "
        f"count; deterministic on re-run). This replaces the old ~200 B guess.\n\n"
        f"{render_table(points)}\n"
        f"Occupancy (entries in window) scales linearly with the event count, and "
        f"the per-exposure cost is flat across the curve — exactly the "
        f"`exposure_rate × window × per-exposure-bytes` shape. `tracemalloc` peak "
        f"is shown only as an independent cross-check; it is allocation-"
        f"nondeterministic and is not the asserted number.\n\n"
        f"**Extrapolation** (the per-exposure cost is measured; the rate and the "
        f"product are still order-of-magnitude sizing, not benchmarked capacity):\n\n"
        f"```\n"
        f"{EXTRAP_RATE_PER_SEC:,} /s × {EXTRAP_WINDOW_SECONDS:,} s "
        f"≈ {total_exposures / 1e10:.1f} × 10¹⁰ exposures  →  ~{tb:.1f} TB "
        f"at the measured ~{anchor:.0f} B/exposure\n"
        f"```\n"
        f"{_END}"
    )


def write_scaling_md(points: list[CurvePoint]) -> None:
    text = SCALING_MD.read_text()
    if _BEGIN not in text or _END not in text:
        raise RuntimeError(
            f"{SCALING_MD.name}: scale-curve markers not found — expected "
            f"{_BEGIN!r} … {_END!r} around the measured section."
        )
    head, rest = text.split(_BEGIN, 1)
    _, tail = rest.split(_END, 1)
    SCALING_MD.write_text(head + render_block(points) + tail)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--no-write",
        action="store_true",
        help="print the curve but do not rewrite docs/SCALING.md",
    )
    args = parser.parse_args(argv)
    points = run_curve()
    for p in points:
        print(
            f"tier {p.n_exposures:>7,}: occupancy {p.exposures_in_window:>7,} "
            f"exposures, {p.bytes_per_exposure:.1f} B/exposure "
            f"({p.structural_bytes / 1e6:.1f} MB structural; "
            f"tracemalloc peak {p.tracemalloc_peak_bytes / 1e6:.1f} MB cross-check; "
            f"engine_join_state_current={p.join_state_current})"
        )
    if not args.no_write:
        write_scaling_md(points)
        print(f"wrote measured curve into {SCALING_MD.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
